# Introduction to rdnb
`r Sys.Date()`  





### About the package

`rdnb` is an R wrapper for the Deutsche Nationalbibliothek (German National Library) API, available at http://www.dnb.de. As the German central archival library, the German National Library is collecting, archiving, bibliographically classifying all German and German-language publications, foreign publications about Germany, translations of German works, and the works of German-speaking emigrants published abroad between 1933 and 1945.

All bibliographic data of the German National Library are provided free of charge and can be freely re-used under "Creative Commons Zero" ([CC0 1.0](http://creativecommons.org/publicdomain/zero/1.0/deed.en)) terms. The metadata and online interfaces are provided with no guarantee of their being continuous, punctual, error-free or complete, or of their not infringing the rights of third parties (e.g. personal rights and copyright).

A personal access token is required for usage and can be requested by sending an e-mail to the Interface Service (schnittstellen-service@dnb.de). The e-mail must include the required catalogue "Catalogue of German National Library (DNB) / Katalog der Deutschen Nationalbibliothek (DNB)" and the access option "via access token / über Zugangscode".

If you do not want to enter your token for each R session, put the following in your .Renviron or .Rprofile file:
`DNB_TOKEN=PUTYOURTOKENHERE`.

#### Source and more details:

[About the DNB](http://www.dnb.de/EN/Wir/wir_node.html); 
[About the interface and access requirements](http://www.dnb.de/EN/Service/DigitaleDienste/SRU/sru_node.html); 
[The DNB web search](http://dnb.dnb.de)


### Package install

`rdnb` is available on CRAN and GitHub. Install from CRAN:


```r
install.packages("rdnb")
```

To install the development version from GitHub the `devtools`-package is required.


```r
if(packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("chgrl/rdnb")
```


### Load the package


```r
library(rdnb)
```


### Search the DNB catalogue

`rdnb` provides two approaches to expose a search. For common search requests use the simple `dnb_search` function. More complex requests are possible using the `dnb_advanced` function.

#### Simple search - `dnb_search`

##### Search for title

Use the `title` parameter to search in titles, including subtitle, short title, volume title, etc.


```r
single.title <- dnb_search(title="katze")
```

A vector of strings combines search terms. Strings in a vector are "OR"-combined by default. Logical operators can be changed by starting a string with `+` or `-`, thus the following code searches for titles containing one of "katze" or "kater", "maus" but not "hund".


```r
multi.title <- dnb_search(title=c("katze", "kater", "+maus", "-hund"))
```

##### Search for author

The `author` parameter offers a search for one or a set of authors. Logical operators can be set as explained above.


```r
single.author.1 <- dnb_search(author="kern")
single.author.2 <- dnb_search(author="kern, ingolf")
single.author.3 <- dnb_search(author="ingolf kern")
author.or.author <- dnb_search(author=c("kern", "locke"))
author.and.author <- dnb_search(author=c("kern", "+locke"))
author.not.author <- dnb_search(author=c("kern", "-locke"))
```

##### Search for publication year

Use the `year` parameter to limit the year(s) of publication. Set `year` to a single integer value to specify a single year. Set the parameter to a sequence to specify start and end. Or set the parameter to a vector of integer values to specify a set of years.


```r
single.year <- dnb_search(title="katze", year=2015)
sequence.of.years <- dnb_search(title="katze", year=2010:2015)
set.of.years <- dnb_search(title="katze", year=c(2010:2013, 2015))
```

##### Search for publisher

Publisher name and/or location may be limited by the `publisher` parameter. Logical operators can be set as explained above.


```r
single.publisher <- dnb_search(title="katze", publisher="kiepenheuer")
single.publisher.location <- dnb_search(title="katze", publisher="*verlag leipzig*")
pub.or.pub <- dnb_search(title="katze", publisher=c("kiepenheuer", "piper"))
pub.and.pub <- dnb_search(title="katze", publisher=c("*kinder*", "+*berlin*"))
pub.not.pub <- dnb_search(title="katze", publisher=c("pi*", "-piper"))
```

##### Search for keyword

Keyword (subjects, persons, locations, organisations, etc.) search is available using the `keyword` parameter. Logical operators can be set as explained for title search.


```r
single.keyword <- dnb_search(keyword ="katze")
keyword.or.keyword <- dnb_search(keyword=c("katze", "hund"))
keyword.and.keyword <- dnb_search(keyword=c("katze", "+hund"))
keyword.not.keyword <- dnb_search(keyword=c("katze", "-hund"))
```

##### Search for type of publication

The DNB discriminates between several publication types:

  * articles (Artikel)
  * manuscript (Manuskripte)
  * biographicaldoc (Lebensdokumente)
  * letters (Briefe)
  * bequest (Nachlässe)
  * collections (Sammlungen)
  * books (Bücher)
  * brailles (Blindenschriften)
  * maps (Karten)
  * discs (Elektronische Datenträger)
  * dissertations (Hochschulschriften)
  * online (Online Ressourcen)
  * films (Filme/Hörbücher)
  * microfiches (Mikrofilm)
  * multimedia (Medienkombinationen)
  * music (Musiktonträger)
  * scores (Noten)
  * serials (Zeitschriften)
  * persons (Personen)
  * subjects (Sachbegriffe)
  * corperations (Organisationen)
  * works (Werke)
  * events (Ereignisse)
  * geographics (Geografika)
  
The `type` parameter can be specified as single string value (named above) or a vector of string values, that will be combined by "OR". Short terms of the available types usually work.


```r
single.type <- dnb_search(title="katze", type="books")
single.type.part <- dnb_search(title="katze", type="bio") # biographicaldoc
set.of.types <- dnb_search(title="katze", type=c("books", "articles", "online"))
```

##### Search for language

The DNB also archives publications in other languages than German, e.g. when they are about Germany or publicated in Germany. The language(s) can be filtered by ISO 639-2/B [code](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/inhaltserschliessung/sprachenCodesEnglisch.pdf?__blob=publicationFile), like "ger" (German), "eng" (English), "fre" (French), "spa" (Spanish) or "gsw" (Swiss German). A vector of string values is combined by "OR".


```r
single.language <- dnb_search(title="cat", language="eng")
set.of.languages <- dnb_search(title=c("cat", "katze"), language=c("eng", "ger"))
```

##### Change limit of results

Use the `limit` parameter to set the number and optionally the starting point of the results returned. A single integer value (possible values: 1-100) specifies the number of results only. Use a vector of two integer values to specify the number of results (first value of vector) and the first result (1 or higher). Set `limit` to "all" for a complete list of results.


```r
first.result <- dnb_search(title="katze", limit=1)
five.results.starting.with.the.21st <- dnb_search(title="katze", limit=c(5, 21))
all.results <- dnb_search(title="katze", year=2016, limit="all")
```

##### Results

Per default no results are printed. Set `print` to `TRUE` to print the `data.frame` with the results.


```r
cats <- dnb_search(title="katze", print=TRUE)
#>            id                        link
#> 1  1097774554 http://d-nb.info/1097774554
#> 2  1097226905 http://d-nb.info/1097226905
#> 3  1100708146 http://d-nb.info/1100708146
#> 4  1088777961 http://d-nb.info/1088777961
#> 5  1098154215 http://d-nb.info/1098154215
#> 6  1079083170 http://d-nb.info/1079083170
#> 7  1096497980 http://d-nb.info/1096497980
#> 8  1100180605 http://d-nb.info/1100180605
#> 9  1101958081 http://d-nb.info/1101958081
#> 10 1101959010 http://d-nb.info/1101959010
#>                                         author
#> 1                         Kanata, Konami (aut)
#> 2                           Lehr, Thomas (aut)
#> 3                      Tinteren, Michael (edt)
#> 4                        Boysen, Margret (aut)
#> 5                        Hofmann, Holger (aut)
#> 6  von Vogel, Maja (aut); Bux, Alexander (ill)
#> 7                        Schöne, Gerhard (aut)
#> 8                         Krön, Gabriele (aut)
#> 9                            Klatt, Arno (aut)
#> 10                           Klatt, Arno (aut)
#>                                                                       title
#> 1                                                 Kleine Katze Chi, Band 11
#> 2                                                            Nabokovs Katze
#> 3                                                           2 treue Freunde
#> 4                                 Alice, der Klimawandel und die Katze Zeta
#> 5                                                           Bär liebt Katze
#> 6                        Bildermaus – Der kleine Fuchs und die freche Katze
#> 7                                                       Bis die Katze bellt
#> 8                                   Clarabella. Die Katze auf der Orgelbank
#> 9  Der Luchs - Der Jäger auf leisen Pfoten (Tischkalender 2017 DIN A5 quer)
#> 10  Der Luchs - Der Jäger auf leisen Pfoten (Wandkalender 2017 DIN A3 quer)
#>                                                      subtitle
#> 1                                                        <NA>
#> 2                                                       Roman
#> 3                                                Katze & Hund
#> 4                                                        <NA>
#> 5                                                        <NA>
#> 6                                                        <NA>
#> 7         Verrückte Kinderlieder aus allen Ecken unserer Welt
#> 8                                             Kleine Episoden
#> 9  Die Katze mit den Pinselohren. (Monatskalender, 14 Seiten)
#> 10 Die Katze mit den Pinselohren. (Monatskalender, 14 Seiten)
#>                             publisher year language          isbn
#> 1                    Carlsen, Hamburg 2017      ger 9783551742902
#> 2    dtv Verlagsgesellschaft, München 2017      ger 9783423145497
#> 3          Coppenrath, Münster, Westf 2016      ger 4050003941981
#> 4             Edition Rugerup, Berlin 2016      ger 9783942955522
#> 5  Gringo Comics, Esslingen am Neckar 2016      ger 9783940047564
#> 6                     Loewe, Bindlach 2016      ger 9783785582008
#> 7                      Jumbo, Hamburg 2016      ger 9783833736476
#> 8                  St. Benno, Leipzig 2016      ger 9783746247922
#> 9              Calvendo, Unterhaching 2016      ger 9783664852062
#> 10             Calvendo, Unterhaching 2016      ger 9783664852055
#>                                                                                                    price
#> 1                                              : EUR 10.30 (AT), sfr 14.90 (freier Preis), EUR 9.95 (DE)
#> 2                             : EUR 15.40 (AT), sfr 19.90 (freier Preis), EUR 14.90 (DE), EUR 14.90 (LU)
#> 3                                                                                                   <NA>
#> 4                                                                Gewebe : EUR 22.60 (AT), EUR 21.90 (DE)
#> 5                                                            Festeinband : EUR 10.10 (AT), EUR 9.80 (DE)
#> 6                                                                Gebunden : EUR 8.20 (AT), EUR 7.95 (DE)
#> 7  in Behältnis : EUR 10.99 (AT) (freier Preis), sfr 14.50 (freier Preis), EUR 10.99 (DE) (freier Preis)
#> 8                                                 Festeinband : circa EUR 8.95 (AT), circa EUR 8.95 (DE)
#> 9                                         : EUR 18.90 (DE) (freier Preis), EUR 19.10 (AT) (freier Preis)
#> 10                                        : EUR 29.90 (DE) (freier Preis), EUR 30.20 (AT) (freier Preis)
#>            pages                 format         edition      keyword
#> 1            160        18 cm x 12.6 cm            <NA>         <NA>
#> 2            512        19.1 cm x 12 cm            <NA>         <NA>
#> 3           <NA>                   63 g      1. Auflage         <NA>
#> 4            278           22 cm, 650 g      1. Auflage Klimatologie
#> 5             54 14.8 cm x 21 cm, 140 g 1., Erstausgabe         <NA>
#> 6             48        24.5 cm x 18 cm            <NA>         <NA>
#> 7  CDs (50 Min.)                   <NA>            <NA>         <NA>
#> 8             80      19.5 cm x 12.5 cm    neue Ausgabe         <NA>
#> 9             14 14.8 cm x 21 cm, 130 g 2. Auflage 2016         <NA>
#> 10            14 29.7 cm x 42 cm, 463 g 2. Auflage 2016         <NA>
#>                               toc
#> 1                            <NA>
#> 2                            <NA>
#> 3                            <NA>
#> 4  http://d-nb.info/1088777961/04
#> 5                            <NA>
#> 6                            <NA>
#> 7                            <NA>
#> 8                            <NA>
#> 9                            <NA>
#> 10                           <NA>
#>                                                                                                description
#> 1  http://deposit.d-nb.de/cgi-bin/dokserv?id=9671f2dd54f743d6af6d9d459de7ace6&prov=M&dok_var=1&dok_ext=htm
#> 2  http://deposit.d-nb.de/cgi-bin/dokserv?id=c7061a6a54f24b4cae3a8d4b05e54651&prov=M&dok_var=2&dok_ext=htm
#> 3  http://deposit.d-nb.de/cgi-bin/dokserv?id=bf2b770b8abf40809f71ebf97a5486a7&prov=M&dok_var=1&dok_ext=htm
#> 4                         https://www.edition-rugerup.de/?product=alice-der-klimawandel-und-die-katze-zeta
#> 5                                                                                                     <NA>
#> 6  http://deposit.d-nb.de/cgi-bin/dokserv?id=233cdda0eb904a09afd5ac8ac1825fdf&prov=M&dok_var=1&dok_ext=htm
#> 7                                                                                                     <NA>
#> 8                                                                                                     <NA>
#> 9  http://deposit.d-nb.de/cgi-bin/dokserv?id=a2808e392970437bbb0349dbc78c57be&prov=M&dok_var=1&dok_ext=htm
#> 10 http://deposit.d-nb.de/cgi-bin/dokserv?id=7c6aa018d3834d3aa7e1a055a40e63d9&prov=M&dok_var=1&dok_ext=htm
#>                                                              cover
#> 1  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-551-74290-2
#> 2  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-423-14549-7
#> 3                                                             <NA>
#> 4  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-942955-52-2
#> 5  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-940047-56-4
#> 6  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-7855-8200-8
#> 7  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-8337-3647-6
#> 8  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-7462-4792-2
#> 9  https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-664-85206-2
#> 10 https://portal.dnb.de/opac/mvb/cover.htm?isbn=978-3-664-85205-5
```

The following data is stored in the `data.frame` (if available):

| Variable | Description |
| --- | --- |
| id | DNB record ID |
| link | link to record |
| author | author(s) |
| title | main title |
| subtitle | subtitle |
| publisher | publisher |
| year | year of publication |
| language | language (abbreviation) |
| isbn | ISBN (13-digit or 10-digit) |
| price | price (as string, usually prices for DE, AT and CH) |
| pages | pages |
| format | size and weight (partial) |
| edition | edition |
| keyword | keyword(s) |
| toc | link to table of contents |
| description | link to description |
| cover | link to cover image |


The total number of records found by the request is stored in the attribute "number_of_records":


```r
attr(cats, "number_of_records")
#> [1] 5618
```

and the query itself can be viewed by calling the "query"-attribute:


```r
attr(cats, "query")
#> [1] "(tit=katze)"
```

You can use this query directly with the `dnb_advanced` function. 


#### Advanced search - `dnb_advanced`

`dnb_advanced` allows for complex requests using the Contextual Query Language (CQL). See the [DNB advanced search help pages](http://www.dnb.de/EN/Header/Hilfe/kataloghilfeExpertensuche.html) for available indices and a list of examples.

The following advanced search returns a list of german or english children's books titled with 'cat', excluding titles containing 'dog', since the year 2001:


```r
cats <- dnb_advanced("( (tit=katze OR tit=kater NOT tit=hund) OR (tit=cat NOT tit=dog) ) AND jhr>2000 AND mat=books AND (spr=ger OR spr=eng) AND sgt=K", limit="all")
```
